version: "3.3"
services:
  bootstrapper:
    image: kollaps:1.0
    command: ["-s", "d77fa641-e6b6-4a28-a750-ca566de27c2e"]
    deploy:
      mode: global
    environment:
      NEED_UUID: 'd77fa641-e6b6-4a28-a750-ca566de27c2e'
      NEED_ORCHESTRATOR: swarm
      NUMBER_OF_GODS: 1
      POOL_PERIOD: 0.05
      MAX_FLOW_AGE: 2
      SHM_SIZE: 8000000000
      AERON_LIB_PATH: /home/daedalus/Documents/aeron4need/cppbuild/Release/lib/libaeronlib.so
      AERON_THREADING_MODE: SHARED
      AERON_TERM_BUFFER_LENGTH: 134217728
      AERON_IPC_TERM_BUFFER_LENGTH: 134217728
    labels:
      bootd77fa641-e6b6-4a28-a750-ca566de27c2e: "true"
    volumes:
      - '/home/user_4/thunderstorm/single_point-to-point.xml:/topology.xml'
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - NEEDnet

  dashboard-d77fa641-e6b6-4a28-a750-ca566de27c2e:
    image: kollaps/dashboard:1.0
    ports:
      - "8088:8088"
    hostname: dashboard
    deploy:
      replicas: 1
    environment:
      NEED_UUID: 'd77fa641-e6b6-4a28-a750-ca566de27c2e'
      NEED_ORCHESTRATOR: swarm
    networks:
      - NEEDnet
      - outside

  logger-d77fa641-e6b6-4a28-a750-ca566de27c2e:
    image: kollaps/logger:1.0
    hostname: logger
    deploy:
      replicas: 1
    environment:
      NEED_UUID: 'd77fa641-e6b6-4a28-a750-ca566de27c2e'
      NEED_ORCHESTRATOR: swarm
    networks:
      - NEEDnet
      - outside

  client1-d77fa641-e6b6-4a28-a750-ca566de27c2e:
    image: kollaps/iperf3-client:1.0
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/NEED_hang; exec /bin/sh <> /tmp/NEED_hang #"]
    command: ['server', '0', '0']
    hostname: client1
    labels:
      d77fa641-e6b6-4a28-a750-ca566de27c2e: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      NEED_UUID: 'd77fa641-e6b6-4a28-a750-ca566de27c2e'
      NEED_ORCHESTRATOR: swarm
    networks:
      - NEEDnet

  server-d77fa641-e6b6-4a28-a750-ca566de27c2e:
    image: kollaps/iperf3-server:1.0
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/NEED_hang; exec /bin/sh <> /tmp/NEED_hang #"]
    hostname: server
    labels:
      d77fa641-e6b6-4a28-a750-ca566de27c2e: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      NEED_UUID: 'd77fa641-e6b6-4a28-a750-ca566de27c2e'
      NEED_ORCHESTRATOR: swarm
    networks:
      - NEEDnet

networks:
  NEEDnet:
    external:
      name: test_overlay
  outside:
    driver: overlay